### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by olavurellefsen**
Merge this into the master branch?

### CODE REVIEW

**Comment by HauHe** [comment]
I think this can be merged, but my preview by vercel doesn't work correctly. When I click on start the screen turns blank. Do you have the same?

**Comment by olavurellefsen** [comment]
The preview works for me on Github, so I will merge it.

**Comment by olavurellefsen** [comment]
I tried merging it and ran into problems after starting the game on Vercel, so I reverted the commit.

**Comment by HauHe** [comment]
I still see the PR as merged. 
Do you have any error message that indicates what might be the issue?

**Comment by olavurellefsen** [comment]
I see the following error in the console in the [Preview](https://reeemgame-git-develop-olavurellefsen.vercel.app/) - after pressing Start.

image

**Comment by olavurellefsen** [comment]
Locally, the error is more verbose. It looks like there is something wrong in MapValues.js line 18; maybe there is some data missing in one of the indicator files (AccumulatedCO2.json, DiscountedInvestmentPerCitizen.json and/or LCOE.json)?

```
  Object.keys(data).forEach(country =>
    colorList.push({
      code: country.toLowerCase(),
      color: convertToColor(data[country], params.min, params.max),
    })
  )
```

image

**Comment by olavurellefsen** [comment]
Yes, it is very likely that no values before 2021 in the indicator Accumulated CO2 is the issue.

**Comment by HauHe** [comment]
Ok, I will need to think about what data to fill before 2021.
For score I just wanted to use the values after 2020, hence the years on which the player has an impact with his decisions.

**Pull request merged**
