### PR TITLE
Update of Accumulated CO2 data

### PR DESCRIPTION
**Pull request by HauHe**
This PR provides a new indicator file for the Accumulated CO2 per citizen, including data for 2015 till 2020

### CODE REVIEW

**Comment by HauHe** [comment]
The deployment looks good to me. I think we can merge it @olavurellefsen

**Comment by HauHe** [comment]
I left the score calculation based on the accumulated Emissions between 2020 and 2050.
Maybe I should mention that somewhere?

**Comment by olavurellefsen** [comment]
> I left the score calculation based on the accumulated Emissions between 2020 and 2050. Maybe I should mention that somewhere?

Yes, you can mention it in the README.md file (or some new documentation file available from there) or in the /about page.

**Comment by HauHe** [comment]
> > I left the score calculation based on the accumulated Emissions between 2020 and 2050. Maybe I should mention that somewhere?
> 
> Yes, you can mention it in the README.md file (or some new documentation file available from there) or in the /about page.

Will prepare something for this in the afternoon and create a new PR.

**Pull request merged**
