### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by olavurellefsen**
Update of Accumulated CO2 data

### CODE REVIEW

**Comment by HauHe** [comment]
Hi @olavurellefsen ,
I think your merge of the 'master into the develop before merging the develop into master overwrote the switch from the co2 intensity to the accumulated co2 emissions.
Could you revert that?

**Comment by olavurellefsen** [comment]
Yes, it looks like I messed it up. I will look into it.

**Comment by olavurellefsen** [comment]
It looks like it is ok now. @HauHe, please check.

**Comment by HauHe** [comment]
Yes, looks good to me too.
I guess we should create a new release. Could you do that?

**Comment by olavurellefsen** [comment]
Done. See https://github.com/olavurellefsen/reeemgame/releases/tag/v1.1.0

**Pull request merged**
