### PR TITLE
Hauke/accu emi

### PR DESCRIPTION
**Pull request by HauHe**
This PR adds the indicator Accumulated CO2 per citizen to the game. The indicator replaces the CO2 intensity in the score calculation. It creates a better distribution of the environmental score and illustrates that not only the emission intensity in 2050 counts but also the emissions on the way there.

### CODE REVIEW

**Comment by HauHe** [comment]
Hm, there seems to be an issue, but I can't see the report by Vercel

**Comment by olavurellefsen** [comment]
When I build it locally (with `npm run build`), I get the following warning:

```
File sizes after gzip:

  2.61 MB  build/static/js/main.c7571eee.js
  2.63 kB  build/static/js/496.492b0e18.chunk.js

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb
```

On the master branch the main file sizes is 2.02 MB (slightly smaller, and working).

**Comment by HauHe** [comment]
Hm, since I added an indicator, perhaps it is related to that. Maybe I remove the data for the CO2 intensity then. Thought it could be nice for comparison, but it is not needed for running the game.

**Comment by HauHe** [comment]
At an earlier point I already rounded the values in the files of the indicators. But I noticed that I haven't done so in the file `score.json` and `scenarioScore.json`.
Before removing the CO2 intensity, I will try if that reduces the size sufficiently

**Comment by HauHe** [comment]
It is working, but when selecting the Accumulated CO2 per citizen and then clicking on a country the values plotted are not for the Accumulated CO2 but the Discounted Investment. 
I searched the file where this is linked but couldn't find it.

**Comment by olavurellefsen** [comment]
When I select the Accumulated CO2 per citizen and then clicking on a country it seems to align with the values shown on the map for Accumulated CO2 per citizen and not Discounted Investment. Can you elaborate on the issue, please?

image

image

**Comment by olavurellefsen** [comment]
Found the error. There was a break missing.

**Comment by HauHe** [comment]
Perfect, thanks so much!

**Pull request merged**
